# Generated by Django 3.1.2 on 2020-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
