# Generated by Django 3.1.2 on 2020-10-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201006_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=True, verbose_name='User'),
        ),
    ]
