# Generated by Django 3.1.2 on 2020-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201006_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
